### ISSUE TITLE
The result of Figure 5

### ISSUE THREAD

**Issue by wjczf123** [thuiar/Adaptive-Decision-Boundary#1]
Can you provide the result of Figure 5?
The results of model (MSP, DOC, OpenMax, DeepUnk, ADB) under different settings (different labeled ratio and different scales of known intents).

**Comment by HanleiZhang** [comment]
Thanks for your suggestion, we have provided results in [results.md](https://github.com/thuiar/Adaptive-Decision-Boundary/blob/main/results/results.md), enjoy it!

**Comment by wjczf123** [comment]
Thank you very much!
