### ISSUE TITLE
questions about metric

### ISSUE THREAD

**Issue by wjczf123** [thuiar/Adaptive-Decision-Boundary#2]
Hi Hanlei,
  Recently, I study many papers on open intent classification. Some questions make me confuse. Can you explain it to me? Thank you!
 1. I notice that the results in Table 2 from [1] are macro f1-score of unknown intent detection. This is different form your ADB method. But i don't find a clear definition of unknown intent detection. And it seems not mean the macro f1-score of open class like Table 3 in ADB.
 2. And what do you think the difference between open intent classification and out-of-domain (out-of-scope) intent detection? 
 3. The metric is confuse. AUROC, AUPR, and so on are used in out-of-domain [2]. I notice that the metric is used often is OOD paper. But it is merely used in open intent classification or unknown intent detection task. What your idea about this?

Finally, thank you a lot.  

1. Deep Unknown Intent Detection with Margin Loss 
2. Out-of-Domain Detection for Natural Language Understanding in Dialog Systems

**Comment by HanleiZhang** [comment]
Hi, thanks for your valuable questions and attention to our series of works. I will try to explain your concerns.  

1. The [metric](https://github.com/thuiar/DeepUnkID/blob/master/utils.py) used in [1] is the macro f1-score of unknown intents. This metric is the same as the macro f1-score on the **open** class in Table 3 of this work. Besides, DeepUnk [1] uses only the macro f1-score on the open (unknown) class, while we also calculate the macro f1-score on all classes (Table 2), known classes and open class (Table 3).   
2. I think there are no differences between open intent classification and out-of-domain intent detection if they are both defined as an N+1 classification task. That is, it aims to identify N known classes and detect the one open class. Moreover, in this work, open class is the same meaning as the unknown class in [1]. Recently, a new work in this area accepted in ACL 21, [Out-of-Scope Intent Detection with Self-Supervision and Discriminative Training](https://arxiv.org/pdf/2106.08616.pdf), also has the same opinion.  
3. Our work follows the previous works [1, 2, 3] to calculate the macro-f1 score as the evaluation metric. In my opinion, some metrics in out-of-domain, such as AUROC, AUPR you mentioned, will be more helpful to observe the performance of the open class.

Related Works:  
1. Deep Unknown Intent Detection with Margin Loss
2. DOC: Deep Open Classification of Text Documents
3. Breaking the Closed World Assumption in Text Classification

**Comment by wjczf123** [comment]
Thank you very much for your reply. But I found that the macro f1-score of unknown intent detection looks the same as open classification recently:
[1] writes ''We use macro F1-score over 5 + 1 classes (1 for rejection) for evaluation.''
[2] writes 'For test utterances of seen intents, the unknown intent detection system aims to assign correct intent labels to them.
For test utterances of unseen intents, the system is expected to identify them as outliers.'
[3] writes ''the primary goal of an unknown intent detection model is to assign correct intent labels to utterances in the test set.''

[1] DOC: Deep Open Classification of Text Documents
[2] Unknown Intent Detection Using Gaussian Mixture Model with an Application to Zero-shot Intent Classification
[3] Out-of-Scope Intent Detection with Self-Supervision and Discriminative Training

**Comment by HanleiZhang** [comment]
Yes, I agree with that the macro f1-score of unknown intent detection is the same as open classification. Thanks for your detailed discussion!

**Comment by wjczf123** [comment]
It means the macro f1-score of unknown intent detection is the same as open classification in [1]? Or it means as you said (This metric is the same as the macro f1-score on the open class in Table 3 of this work. )? Because I cann't find a definition of this paper. And this paper comes from your group.

[1] Deep Unknown Intent Detection with Margin Loss

**Comment by HanleiZhang** [comment]
Hi, I know what your question is. Let me clarify it. The overall macro f1-score of open classification and unknown intent detection is the macro f1-score over all classes (N known classes and one open class). The macro f1-score over the open (unknown) class is defined as in [1]. That is, [1] essentially calculates the macro f1-score over the unknown class, but it does not state it clearly (to distinguish it with the normal macro f1-score over all classes). In conclusion, I strongly recommend clarifying whether it is overall macro f1-score or fine-grained macro f1-score in this work.  

[1] Deep Unknown Intent Detection with Margin Loss

**Comment by wjczf123** [comment]
OK. Thank you very much for your reply. Best wishes!
