### ISSUE TITLE
A problem about pretrainded model

### ISSUE THREAD

**Issue by ZhWL123456** [thuiar/Adaptive-Decision-Boundary#3]
I config the bert_model as ./pretrained_models/uncased_L-12_H-768_A-12.
But I face the error as follow：
Model name './pretrained_models/uncased_L-12_H-768_A-12' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed './pretrained_models/uncased_L-12_H-768_A-12' was a path or url but couldn't find any file associated to this path or url.
Can u help me?

**Comment by ZhWL123456** [comment]
I change the bert_model as bert-base-uncased. There is still a problem that "Model name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz' was a path or url but couldn't find any file associated to this path or url. "

**Comment by HanleiZhang** [comment]
Hi, we get the pre-trained [BERT](https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip) model and convert it into [Pytorch](https://huggingface.co/transformers/converting_tensorflow_models.html). As you mentioned, it is a URL path set in the parameters. For convenience,  we release the converted bert pre-trained model of pytorch-version in [Baidu Cloud Drive](https://pan.baidu.com/s/1k1zxK4xh0UyPhOU_-oPlow) with code: v8tk. 

> I config the bert_model as ./pretrained_models/uncased_L-12_H-768_A-12. But I face the error as follow： Model name './pretrained_models/uncased_L-12_H-768_A-12' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed './pretrained_models/uncased_L-12_H-768_A-12' was a path or url but couldn't find any file associated to this path or url. Can u help me?

**Comment by ZhWL123456** [comment]
Thank u~ Finally, I solved it!
